app/authentication/models.py
from peewee import CharField
from flask_login import UserMixin

from app.base_model import BaseModel


class AuthUser(UserMixin, BaseModel):
    email = CharField(max_length=150, unique=True, index=True)
    password = CharField(max_length=100, null=True)
    name = CharField(max_length=100, null=True)

app/authentication/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, EmailField, SubmitField, HiddenField, PasswordField
from wtforms.validators import DataRequired, Length


class RegisterForm(FlaskForm):
    id = HiddenField('id')
    name = StringField(
        'Your nickname',
        validators=[DataRequired(), Length(3, 100)],
        render_kw={'placeholder': 'Full name'}
    )
    email = EmailField(
        'Your email',
        validators=[DataRequired(), Length(10, 150)],
        render_kw={'placeholder': 'Email'}
    )
    password = PasswordField(
        'Your password',
        validators=[DataRequired(), Length(8, 100)],
        render_kw={'placeholder': 'Password'}
    )
    submit = SubmitField('Register')


class UserForm(FlaskForm):
    email = EmailField(
        'Your email',
        validators=[DataRequired(), Length(10, 150)],
        render_kw={'placeholder': 'Email'}
    )
    password = PasswordField(
        'Your password',
        validators=[DataRequired(), Length(8, 100)],
        render_kw={'placeholder': 'Password'}
    )
    login = SubmitField('Login')

app/authentication/__init__.py
from flask import Blueprint

authentication = Blueprint('authentication', __name__, url_prefix='/authentication')

from app.authentication import routes

app/authentication/routes.py
from flask import (
    render_template,
    redirect,
    url_for,
    flash
)
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required, current_user

from app.authentication import authentication
from .models import AuthUser
from .forms import RegisterForm, UserForm


@authentication.route('/login', methods=['POST', 'GET'])
def login():

    form = UserForm()

    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        user = AuthUser.filter(email=email).first()
        if not AuthUser.select().where(AuthUser.email == email, check_password_hash(user.password, password)):
            flash('Please check your login details and try again.')
            return redirect(url_for('authentication.login'))
        login_user(user)
        return redirect(url_for('authentication.profile'))

    return render_template(
        'authentication/login.html',
        title='Login',
        form=form
    )


@authentication.route('/profile')
@login_required
def profile():
    return render_template(
        'authentication/profile.html',
        name=current_user.name
    )


@authentication.route('/signup', methods=['POST', 'GET'])
def signup():

    form = RegisterForm()

    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data
        password = form.password.data
        user = AuthUser.filter(email=email).first()
        message = f'User with name {name} already registered'
        if not AuthUser.select().where(AuthUser.email == email, AuthUser.password == password):
            user = AuthUser(name=name, email=email, password=generate_password_hash(password, method='sha256'))
            user.save()
            message = f'User with name {name} just registered'
        flash(message)

    return render_template(
        'authentication/signup.html',
        title='Sign up',
        form=form
    )


@authentication.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('authentication.login'))

app/templates/authentication/login.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
    <div class="column is-4 is-offset-4">
        <h3 class="title">Login</h3>
        <div class="box">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <div class="notification is-danger">
                        {{ messages[0] }}
                    </div>
                {% endif %}
            {% endwith %}
            <form action="{{ url_for('authentication.login') }}" method="POST" action="/login">
                {{ form.csrf_token }}
                {{ wtf.form_field(form.email) }}
                {{ wtf.form_field(form.password) }}
                {{ wtf.form_field(form.login) }}
            </form>
            <h5><a href="{{ url_for('authentication.signup') }}" > Sign up </a></h5>
        </div>
    </div>
{% endblock page_content %}

app/templates/authentication/profile.html
{% extends "_base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <h1 class="title" align="center">
        Welcome, {{ name }}! This is your profile.
    </h1>
    <h3>{{ email }}</h3>
{% endblock %}

app/templates/authentication/signup.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
    {{ title }}
{% endblock title %}

{% block page_content %}
    <div class="page-header">
        <h1>Sign up</h1>
    </div>
    {% include 'messages.html' %}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }} Go to <a href="{{ url_for('authentication.login') }}">login page</a>.
            </div>
        {% endif %}
    {% endwith %}
    <form action="{{ url_for('authentication.signup') }}" method="POST">
        {{ form.csrf_token }}
        {{ wtf.form_field(form.name) }}
        {{ wtf.form_field(form.email) }}
        {{ wtf.form_field(form.password) }}
        {{ wtf.form_field(form.submit) }}
    </form>
{% endblock page_content%}